### ISSUE TITLE
upgrade from 1.3.x to 1.4.x results in `Cannot find module 'util/types'`

### ISSUE THREAD

**Issue by steveliles** [SalvatorePreviti/roaring-node#46]
Upgrading from roaring@1.3.0 to roaring@1.4.x with no other changes in my project I get:

`Cannot find module 'util/types' from 'node_modules/roaring/index.js'`

Everything works and my tests are green with 1.3.0, but cannot run tests or app with 1.4.x

node version: 14.19.3
npm version: 6.14.17

jest tests fail:

```
    Cannot find module 'util/types' from 'node_modules/roaring/index.js'

    Require stack:
      node_modules/roaring/index.js
      src/cypher/projection.js
      src/cypher/cypher.js
      src/cypher/index.js
      src/index.js
      src/index.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/roaring/index.js:26:54)
```

and the app itself will not run:

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'util/types'
Require stack:
- /Users/steve/dev/DataLanguage/datagraphs/datagraphs-inmemory-graph-api/node_modules/roaring/index.js
- ...
- ...
- /Users/steve/dev/DataLanguage/datagraphs/datagraphs-inmemory-graph-api/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/steve/dev/DataLanguage/datagraphs/datagraphs-inmemory-graph-api/node_modules/roaring/index.js:26:54)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/steve/dev/DataLanguage/datagraphs/datagraphs-inmemory-graph-api/node_modules/roaring/index.js',
    ...
```

**Comment by SalvatorePreviti** [comment]
Thank you for reporting, should be fixed in the new version I am releasing now.
