### ISSUE TITLE
OS agnostic

### ISSUE THREAD

**Issue by apmovamo** [SalvatorePreviti/roaring-node#58]
```
Node.js version: v21.1.0
Framework: Nest.js 10
--node_napi_label=node-v120
```

Description: 
The package is not OS agnostic and roaring-node-v120-linux-x64 can not be found. If I am not wrong the v120 is the ABI(Application Binary Interface).

```
/app # npm i roaring
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! path /app/node_modules/roaring
npm ERR! command failed
npm ERR! command sh -c node ./node-pre-gyp.js install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/roaring/native/roaring-node-v120-linux-x64/roaring.node --module_name=roaring --module_path=/app/node_modules/roaring/native/roaring-node-v120-linux-x64 --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp: 1.871s
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@21.1.0 | linux | x64
npm ERR! (node:420) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! node-pre-gyp info check checked for "/app/node_modules/roaring/native/roaring-node-v120-linux-x64/roaring.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/SalvatorePreviti/roaring-node/releases/download/2.2.0/roaring-v2.2.0-node-v120-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/SalvatorePreviti/roaring-node/releases/download/2.2.0/roaring-v2.2.0-node-v120-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for roaring@2.2.0 and node@21.1.0 (node-v120 ABI, musl) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/SalvatorePreviti/roaring-node/releases/download/2.2.0/roaring-v2.2.0-node-v120-linux-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.1
npm ERR! gyp info using node@21.1.0 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.1
npm ERR! gyp info using node@21.1.0 | linux | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/app/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/app/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/app/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:430:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:442:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:515:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:484:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Linux 6.4.16-linuxkit
npm ERR! gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/roaring/native/roaring-node-v120-linux-x64/roaring.node" "--module_name=roaring" "--module_path=/app/node_modules/roaring/native/roaring-node-v120-linux-x64" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v120"
npm ERR! gyp ERR! cwd /app/node_modules/roaring
npm ERR! gyp ERR! node -v v21.1.0
npm ERR! gyp ERR! node-gyp -v v9.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/roaring/native/roaring-node-v120-linux-x64/roaring.node --module_name=roaring --module_path=/app/node_modules/roaring/native/roaring-node-v120-linux-x64 --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:515:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Linux 6.4.16-linuxkit
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/roaring/node-pre-gyp.js" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /app/node_modules/roaring
npm ERR! node-pre-gyp ERR! node -v v21.1.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-30T10_17_04_991Z-debug-0.log
```

**Comment by SalvatorePreviti** [comment]
I did not release yet a version compatible with node 21, the latest compatible version is node 20

**Comment by SalvatorePreviti** [comment]
For more information on NodeJs release and version strategy, https://nodejs.org/en/about/previous-releases#

**Comment by apmovamo** [comment]
> I did not release yet a version compatible with node 21, the latest compatible version is node 20. Consider that node 20 is the Long Term Support and the odd number version of node are not stable and should not be used in production. Only even mode versions should be used in production

Yeah clear but one more think is that some Node projects which use docker may install packages on the host machine e.x. MacOS and run the project on Docker environment(linux). Which package will install be installed in host(MacOS, darwin) and which is need to run on docker linux?

**Comment by SalvatorePreviti** [comment]
There is also a webassembly stripped down version of this library that offers less features, a bit more difficult API and is much slower but is platform independent- see roaring-wasm that I maintain as well
